# Generated by Django 5.2.8 on 2025-11-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='user_type',
        ),
    ]
